### ISSUE TITLE
EEPROM64K(8kb) save files improperly loaded

### ISSUE THREAD

**Issue by Uvik** [libretro/vbam-libretro#33] opened 2017-07-04 19:36 UTC
With the vbam_libretro core in Retroarch, it looks like 8kb EEPROM64K save files (the name might be wrong, my apologies in advance) are not properly loaded.

Upon save, the emulator overwrites the original 8192b save file with an empty one weighing 139264 bytes.

Reliably reproduced the issue with the latest vba_next_libretro core as well (reported the same issue under [VBA-Next issue #83](https://github.com/libretro/vba-next/issues/83), but both mgba_libretro and the latest standalone release of VBA-M (taken from commit 2e8bee1) load my save files just fine.

It might be important to add that I got these issues by loading *my own GBA ROMs and save files*, dumped from my original cartridges using a DS linker and a backup tool. Coming straight from the cartridges, they are completely unaltered and the incompatibility might be expected (who knows?).

I noticed the issue with the following ROMs (with the names retrieved by the backup tool, just in case):
- The Legend of Zelda: A Link to the Past + Four Swords - EU version (GBAZELDA_AZLP00)
- The Legend of Zelda: The Minish Cap - EU version (GBAZELDA_MC_BZMP00)
- Mario & Luigi: Superstar Saga - EU version (MARIO_LUIGIP_A88P00)
- Tales of Phantasia - EU version (PHANTASIA_AN8P00)
- Super Mario Advance 2: Super Mario World - EU version (SUPER_MARIOB_AA2P00)

All of these games seem to use the same 8kb EEPROM64K save format.

Please let me know if you require any information. I am obviously uncomfortable with sharing the ROMs I dumped, but I can provide problematic save files if required.

Thank you in advance !

P.S.: After a quick glance at the code, it looks like the libretro workaround (defined at EEprom.cpp, line 14) might be related in one way of the other. At least, that seems to be why the save file ends up being 139264 bytes large after loading it. I have no idea about the rationale behind this workaround though, so my guess could very well be utterly wrong :-)

**Comment by retro-wertz** [comment] 2018-05-20 03:51
not a bug, just how retroarch handles savefile when there more than just one variable to save (sram + eeprom) and with varying sizes. the workaround is to set a fixed size instead which contains these two save types. so the saves are not compatible (at least directly or without hex editing) with standalone, but it should not be an issue when just used with the associated core.

**Comment by retro-wertz** [comment] 2018-05-21 04:51
UPDATE: after re-checking this libretro handling for save file, it seems that its possible to actually use the correct savefile size since its not possible to enabled both sram/flash ram & eeprom save file type (needs confirmation and or checking games, but so far code seems to indicated that both are not used).

dunno why libretro is doing this though.

**Comment by retro-wertz** [comment] 2019-01-21 21:17
proper save file types and sizes for most games should now be identified with the latest commit (EEPROM_512, EEPROM_8K, SRAM 32K, FLASH_512K and FLASH_1M)

please post if there are games which are not detected properly

**Comment by hizzlekizzle** [comment] 2019-08-13 02:03
alright, since there haven't been any more reports, I'm going to close this issue.

**Closed by hizzlekizzle** 2019-08-13 02:03 UTC
