### ISSUE TITLE
Keyboard buttons messed up with newer RA version

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/vbam-libretro#32] opened 2017-07-04 03:27 UTC
Keyboards buttons are messed up, Enter is Down for example. Right and Left are Up.

It's fine with gamepads.

The samething happens with VBA Next.

It was working fine with RA 1.3.6.

Xubuntu 17.04 64-bit

Edit: clear config

**Comment by fr500** [comment] 2017-07-04 03:30
uhh... there is no keyboard polling directly on the core
I can't reproduce this at all

**Comment by retro-wertz** [comment] 2018-05-20 03:52
works fine here.

**Comment by hizzlekizzle** [comment] 2019-08-13 02:03
I'm going to close this issue, as it seems to be invalid/resolved. If not, feel free to reopen.

**Closed by hizzlekizzle** 2019-08-13 02:03 UTC
